import React, { Component } from "react";
import Checkbox from '@material-ui/core/Checkbox'
import FormControlLabel from '@material-ui/core/FormControlLabel'
import FormControl from '@material-ui/core/FormControl'
import red from '@material-ui/core/colors/red'
import white from '@material-ui/core/colors/'
import {MuiFormControlLabel, MuiThemeProvider} from '@material-ui/core/styles'
import { createMuiTheme, Backdrop } from "@material-ui/core";
import { withStyles } from "@material-ui/styles";
import color from "@material-ui/core/colors/amber";
import './RandomPlayerSelector.scss' 
// import classes from "*.module.css";


// const theme = createMuiTheme({
//     overrides: {
//         root: {
//     FormControlLabel: {
//         label: {
    
//         color: 'secondary'
        
//     }
// }
//     }
// },
//     checked: {}
// });

// Class Name: RandomPlayerSelector
// Class Usage: found in nav bar
// Class Reason: to randomly select a player from a selected group of players

class RandomPlayerSelector extends Component {
    state = {
        // Reason: will list players currently playing
        players: [
            {name: "player 1"},
            {name: "player 2"},
            {name: "player 3"},
<<<<<<< HEAD
            {name: "player 4"}
=======
            {name: "player 4"}        
>>>>>>> 38b6f2e70218b6d47be3f4496242a0a408f78439
        ],
        // Reason: holds players who are selected in the state
        selectedPlayers: [],
<<<<<<< HEAD
    }
// Function Name: onChange
// Function Usage: used by checkboxes generated by generatePlayer
// Function Reason: event listener that gets called everytime a checkbox is clicked and update the state based off which players are selected
=======
        isChecked: false
        }



        



    //taken from internet
>>>>>>> 38b6f2e70218b6d47be3f4496242a0a408f78439
    onChange(e) {
        //gets current state of players from json
        let selectedPlayers = this.state.selectedPlayers;
        //determines position in array
        let index
        if (e.target.checked) {
            selectedPlayers.push(e.target.value);
        } else {
            index = selectedPlayers.indexOf(e.target.value);
            selectedPlayers.splice(index, 1)
        }
        this.setState({selectedPlayers: selectedPlayers})
    }
// Function Name: randPlayer
// Function Usage: used on generate button
// Function Reason: calculates random player from players selected and displays chosen player as an alert
    randPlayer = () => {
<<<<<<< HEAD
                // Reason:
=======
       
>>>>>>> 38b6f2e70218b6d47be3f4496242a0a408f78439
        const thisPlayer = this.state.selectedPlayers[Math.floor(Math.random() * this.state.selectedPlayers.length)]
        return(
        alert(thisPlayer)
        )
    }
<<<<<<< HEAD
    // Function Name: onChange
    // Function Usage: used by checkboxes generated by generatePlayer
    // Function Reason:
    generatePlayer = (players) => {
=======



    generatePlayer = (player) => {
>>>>>>> 38b6f2e70218b6d47be3f4496242a0a408f78439
        return(
            <FormControlLabel 
            id={player.name}
            value={player.name}
            checked={Checkbox.checked} 
            control={
                <Checkbox 
                     /> 
                } 
            label={player.name} 
            onChange={this.onChange.bind(this)}
             />
                        
        )
    }
    // Function Name: onChange
    // Function Usage: used by checkboxes generated by generatePlayer
    // Function Reason:
    render() {

        return(
            // <MuiThemeProvider theme={theme}>
            <div>
<<<<<<< HEAD
            {/* Function Name: onChange
                Function Usage: used by checkboxes generated by generatePlayer
                Function Reason: */}
=======

            <FormControl>
>>>>>>> 38b6f2e70218b6d47be3f4496242a0a408f78439
                {this.state.players.map(
                        (player, i) =>
                            <this.generatePlayer
                                key={i}
                                name={player.name}/>
                    )}
<<<<<<< HEAD
                    {/*should generate random player and display it*/}
            {/* Function Name: onChange
                Function Usage: used by checkboxes generated by generatePlayer
                Function Reason: */}
=======
>>>>>>> 38b6f2e70218b6d47be3f4496242a0a408f78439
                <button onClick={this.randPlayer.bind(this)}>
                    Generate
                </button>
            </FormControl>

                    {/*should generate random player and display it*/}


                <div>
                    
                </div>

            </div>
            // </MuiThemeProvider>

        )
    }
}



export default RandomPlayerSelector;